#![forbid(unsafe_code)]
use std::{env,fs,path::{Path,PathBuf}};
use leader_core::{build_topology,Machine};
use leader_svg::{render,RenderConfig};
fn main(){if let Err(e)=run(){eprintln!("leader-cli: {e}");std::process::exit(1)}}
fn run()->Result<(),String>{let mut a=env::args().skip(1);let cmd=a.next().unwrap_or_else(||"render".into());let opt=Options::parse(a.collect())?;match cmd.as_str(){"render"=>render_cmd(opt),"trace"=>trace_cmd(opt),"stats"=>stats_cmd(opt),"help"|"--help"|"-h"=>{help();Ok(())},x=>Err(format!("unknown command '{x}'"))}}
#[derive(Debug,Clone)]struct Options{seed:String,output:PathBuf,max_frames:u32}
impl Options{fn parse(a:Vec<String>)->Result<Self,String>{let(mut seed,mut output,mut max)=("leader-invader-dev".to_owned(),PathBuf::from("generated/Leader.svg"),5000u32);let mut i=0;while i<a.len(){match a[i].as_str(){"--seed"=>{i+=1;seed=a.get(i).ok_or("--seed requires value")?.clone()},"--output"|"-o"=>{i+=1;output=PathBuf::from(a.get(i).ok_or("--output requires path")?)},"--max-frames"=>{i+=1;max=a.get(i).ok_or("--max-frames requires value")?.parse().map_err(|e|format!("invalid frame count: {e}"))?},x=>return Err(format!("unknown option '{x}'"))}i+=1}Ok(Self{seed,output,max_frames:max})}}
fn render_cmd(o:Options)->Result<(),String>{let t=build_topology();let tr=Machine::run_match(&o.seed,o.max_frames);if!tr.finished{return Err(format!("match did not clear within {} frames",o.max_frames))}let svg=render(&t,&tr,RenderConfig::default());write(&o.output,svg.as_bytes())?;let tp=o.output.with_file_name("trace.json");write(&tp,tr.to_json().as_bytes())?;println!("rendered {} nodes / {} links / {} frames / {} kills -> {}",t.nodes.len(),t.links.len(),tr.total_frames,tr.kills.len(),o.output.display());Ok(())}
fn trace_cmd(mut o:Options)->Result<(),String>{if o.output==PathBuf::from("generated/Leader.svg"){o.output=PathBuf::from("generated/trace.json")}let tr=Machine::run_match(&o.seed,o.max_frames);write(&o.output,tr.to_json().as_bytes())?;println!("frames={} kills={} clear={}",tr.total_frames,tr.kills.len(),tr.finished);if tr.finished{Ok(())}else{Err("trace hit frame limit".into())}}
fn stats_cmd(o:Options)->Result<(),String>{let t=build_topology();let tr=Machine::run_match(&o.seed,o.max_frames);println!("topology.nodes={}",t.nodes.len());println!("topology.links={}",t.links.len());println!("trace.frames={}",tr.frames.len());println!("trace.micro_samples={}",tr.micro_samples.len());println!("trace.kills={}",tr.kills.len());println!("trace.finished={}",tr.finished);println!("trace.final_score={}",tr.final_score);Ok(())}
fn write(p:&Path,b:&[u8])->Result<(),String>{if let Some(parent)=p.parent(){fs::create_dir_all(parent).map_err(|e|format!("cannot create {}: {e}",parent.display()))?}fs::write(p,b).map_err(|e|format!("cannot write {}: {e}",p.display()))}
fn help(){println!("leader-cli\n\nrender [--seed TEXT] [--output PATH] [--max-frames N]\ntrace  [--seed TEXT] [--output PATH]\nstats  [--seed TEXT]\n\nSame source + same seed => same deterministic replay.")}
