use crate::logic::{
    logic_trace, ripple_add, ripple_decrement16, ripple_increment16, ripple_sub, AluOp,
    AluTrace, PcIncrementTrace,
};
use crate::microcode::{
    control_word_at, decode as decode_microcode, execute_address, internal, uaddr, ControlWord,
    MicroAddressTransition, MicroOp, MicroSequencer,
};
use crate::trace::{ControlLatchKind, PhaseKind};

pub mod op {
    pub const NOP: u8 = 0x00; pub const LDI: u8 = 0x10; pub const LD: u8 = 0x11; pub const ST: u8 = 0x12; pub const MOV: u8 = 0x13;
    pub const ADD: u8 = 0x20; pub const ADDI: u8 = 0x21; pub const SUBI: u8 = 0x22; pub const ANDI: u8 = 0x23; pub const ORI: u8 = 0x24; pub const XORI: u8 = 0x25; pub const INC: u8 = 0x26; pub const DEC: u8 = 0x27; pub const CMP: u8 = 0x28; pub const CMPI: u8 = 0x29;
    pub const JMP: u8 = 0x30; pub const JZ: u8 = 0x31; pub const JNZ: u8 = 0x32; pub const JLT: u8 = 0x33; pub const JGE: u8 = 0x34; pub const JC: u8 = 0x35; pub const CALL: u8 = 0x36; pub const RET: u8 = 0x37;
    pub const WAIT_VBLANK: u8 = 0xFE; pub const HALT: u8 = 0xFF;
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)] #[repr(u8)] pub enum Reg { A=0,B=1,C=2,D=3,X=4,Y=5,T=6,U=7 }
impl Reg { pub const ALL:[Self;8]=[Self::A,Self::B,Self::C,Self::D,Self::X,Self::Y,Self::T,Self::U]; #[must_use] pub const fn code(self)->u8{self as u8} #[must_use] pub const fn name(self)->&'static str{match self{Self::A=>"A",Self::B=>"B",Self::C=>"C",Self::D=>"D",Self::X=>"X",Self::Y=>"Y",Self::T=>"T",Self::U=>"U"}} fn from_code(value:u8)->Option<Self>{Self::ALL.get(value as usize).copied()} }
#[derive(Debug,Clone,Copy,Default,PartialEq,Eq)] pub struct Flags{pub zero:bool,pub carry:bool,pub less:bool}
#[derive(Debug,Clone,Copy,PartialEq,Eq)] pub enum StepOutcome{Continue,WaitVBlank,Halted,Fault{pc:u16,opcode:u8}}
#[derive(Debug,Clone,Copy,PartialEq,Eq)] pub enum PcSource{Jump,Branch,Call,Return}
impl PcSource{#[must_use]pub const fn as_str(self)->&'static str{match self{Self::Jump=>"jump",Self::Branch=>"branch",Self::Call=>"call",Self::Return=>"return"}}}
#[derive(Debug,Clone,Copy,PartialEq,Eq)] pub enum MicroPhase{T0,T1,T2}
impl MicroPhase{#[must_use]pub const fn as_str(self)->&'static str{match self{Self::T0=>"t0",Self::T1=>"t1",Self::T2=>"t2"}}}
#[derive(Debug,Clone,Copy,PartialEq,Eq)] pub enum MicroCycleKind{FetchAddress,FetchData,DecodeLatch,OperandAddress,OperandData,OperandReady,MemoryAddress,MemoryRead,MemoryWriteData,MemoryWriteCommit}
impl MicroCycleKind{#[must_use]pub const fn as_str(self)->&'static str{match self{Self::FetchAddress=>"fetch_address",Self::FetchData=>"fetch_data",Self::DecodeLatch=>"decode_latch",Self::OperandAddress=>"operand_address",Self::OperandData=>"operand_data",Self::OperandReady=>"operand_ready",Self::MemoryAddress=>"memory_address",Self::MemoryRead=>"memory_read",Self::MemoryWriteData=>"memory_write_data",Self::MemoryWriteCommit=>"memory_write_commit"}}}

pub trait Bus{
    fn fetch8(&mut self,pc:u16)->u8; fn read8(&mut self,pc:u16,address:u16)->u8; fn write8(&mut self,pc:u16,address:u16,value:u8); fn trace_decode(&mut self,pc:u16,opcode:u8,mnemonic:&'static str); fn trace_alu(&mut self,pc:u16,value:u8,control:&'static str); fn trace_control(&mut self,pc:u16,control:&'static str);
    fn trace_alu_exact(&mut self,pc:u16,trace:AluTrace,control:&'static str){self.trace_alu(pc,trace.result,control)}
    fn trace_flags(&mut self,_pc:u16,_flags:Flags,_control:&'static str){}
    fn trace_control_latch(&mut self,_pc:u16,_kind:ControlLatchKind,_value:u16,_valid:bool,_control:&'static str){}
    fn trace_register_write(&mut self,_pc:u16,_reg:Reg,_before:u8,_after:u8,_control:&'static str){} fn trace_pc_increment(&mut self,_trace:PcIncrementTrace){} fn trace_pc_load(&mut self,_before:u16,_after:u16,_source:PcSource,_control:&'static str){}
    fn trace_microaddress(&mut self,_transition:MicroAddressTransition,_opcode:u8,_control_bits:u32,_label:&'static str){}
    fn trace_microcycle(&mut self,phase:MicroPhase,_kind:MicroCycleKind,pc:u16,_mar:u16,_mdr:u8,_ir:u8,_control:&'static str){let timing=match phase{MicroPhase::T0=>"µT0",MicroPhase::T1=>"µT1",MicroPhase::T2=>"µT2"};self.trace_control(pc,timing);}
}

#[derive(Debug,Clone,PartialEq,Eq)]
pub struct Cpu{regs:[u8;8],pc:u16,sp:u16,mar:u16,mdr:u8,ir:u8,phase:MicroPhase,micro:MicroSequencer,reg_a:Option<Reg>,reg_b:Option<Reg>,alu_a:u8,alu_b:u8,alu_op:Option<AluOp>,address_lo:u8,address_hi:u8,condition_latch:bool,pc_selected:Option<u16>,flags:Flags,halted:bool}
impl Default for Cpu{fn default()->Self{Self{regs:[0;8],pc:0,sp:0x7FFF,mar:0,mdr:0,ir:0,phase:MicroPhase::T0,micro:MicroSequencer::default(),reg_a:None,reg_b:None,alu_a:0,alu_b:0,alu_op:None,address_lo:0,address_hi:0,condition_latch:false,pc_selected:None,flags:Flags::default(),halted:false}}}

impl Cpu{
    #[must_use]pub const fn pc(&self)->u16{self.pc} #[must_use]pub const fn sp(&self)->u16{self.sp} #[must_use]pub const fn mar(&self)->u16{self.mar} #[must_use]pub const fn mdr(&self)->u8{self.mdr} #[must_use]pub const fn ir(&self)->u8{self.ir} #[must_use]pub const fn phase(&self)->MicroPhase{self.phase} #[must_use]pub const fn micro_address(&self)->u8{self.micro.address()} #[must_use]pub const fn flags(&self)->Flags{self.flags} #[must_use]pub fn reg(&self,reg:Reg)->u8{self.regs[reg as usize]}
    pub fn step<B:Bus>(&mut self,bus:&mut B)->StepOutcome{if self.halted{return StepOutcome::Halted;}let instruction_pc=self.pc;let opcode=self.fetch_opcode(bus);let Some(micro)=decode_microcode(self.ir)else{return self.fault(instruction_pc,self.ir);};let Some(exec)=execute_address(self.ir)else{return self.fault(instruction_pc,self.ir);};let transition=self.micro.dispatch(exec);self.publish_microaddress(bus,transition,micro.mnemonic);bus.trace_decode(instruction_pc,self.ir,micro.mnemonic);match micro.operation{
        MicroOp::Nop=>StepOutcome::Continue,
        MicroOp::LoadImmediate=>{let Some(reg)=self.next_reg(bus)else{return self.fault(instruction_pc,opcode);};self.latch_register_select_traced(bus,instruction_pc,reg,micro.mnemonic);self.advance_execute(bus,"LDI_VALUE");let value=self.next8(bus);self.latch_operand_b(value);self.latch_alu_op(AluOp::Pass);self.advance_execute(bus,"LDI_COMMIT");let Some(trace)=self.propagate_latched_alu(bus,instruction_pc,micro.mnemonic,false)else{return self.fault(instruction_pc,opcode);};if !self.write_selected_a(bus,instruction_pc,trace.result,micro.mnemonic){return self.fault(instruction_pc,opcode);}StepOutcome::Continue},
        MicroOp::LoadMemory=>self.load_memory(bus,instruction_pc,opcode,micro.mnemonic),MicroOp::StoreMemory=>self.store_memory(bus,instruction_pc,opcode),MicroOp::Move=>self.binary_register_alu(bus,instruction_pc,opcode,AluOp::Pass,micro.mnemonic,false),MicroOp::Add=>self.binary_register_alu(bus,instruction_pc,opcode,AluOp::Add,micro.mnemonic,false),MicroOp::AddImmediate=>self.immediate_arithmetic(bus,instruction_pc,opcode,AluOp::Add,micro.mnemonic),MicroOp::SubImmediate=>self.immediate_arithmetic(bus,instruction_pc,opcode,AluOp::Sub,micro.mnemonic),MicroOp::AndImmediate=>self.immediate_logic(bus,instruction_pc,opcode,AluOp::And,micro.mnemonic),MicroOp::OrImmediate=>self.immediate_logic(bus,instruction_pc,opcode,AluOp::Or,micro.mnemonic),MicroOp::XorImmediate=>self.immediate_logic(bus,instruction_pc,opcode,AluOp::Xor,micro.mnemonic),MicroOp::Increment=>self.unary_arithmetic(bus,instruction_pc,opcode,true),MicroOp::Decrement=>self.unary_arithmetic(bus,instruction_pc,opcode,false),MicroOp::Compare=>self.binary_register_alu(bus,instruction_pc,opcode,AluOp::Compare,micro.mnemonic,true),MicroOp::CompareImmediate=>self.compare_immediate(bus,instruction_pc,opcode,micro.mnemonic),MicroOp::Jump=>self.control_transfer(bus,instruction_pc,true,PcSource::Jump,micro.mnemonic),MicroOp::JumpZero=>self.control_transfer(bus,instruction_pc,self.flags.zero,PcSource::Branch,micro.mnemonic),MicroOp::JumpNotZero=>self.control_transfer(bus,instruction_pc,!self.flags.zero,PcSource::Branch,micro.mnemonic),MicroOp::JumpLess=>self.control_transfer(bus,instruction_pc,self.flags.less,PcSource::Branch,micro.mnemonic),MicroOp::JumpGreaterEqual=>self.control_transfer(bus,instruction_pc,!self.flags.less,PcSource::Branch,micro.mnemonic),MicroOp::JumpCarry=>self.control_transfer(bus,instruction_pc,self.flags.carry,PcSource::Branch,micro.mnemonic),MicroOp::Call=>self.call_subroutine(bus,instruction_pc,micro.mnemonic),MicroOp::Return=>self.return_subroutine(bus,instruction_pc,micro.mnemonic),MicroOp::WaitVBlank=>{bus.trace_control(instruction_pc,micro.mnemonic);StepOutcome::WaitVBlank},MicroOp::Halt=>{self.halted=true;bus.trace_control(instruction_pc,micro.mnemonic);StepOutcome::Halted}}}

    fn active_control(&self)->ControlWord{control_word_at(self.micro.address(),self.ir)} fn internal_enabled(&self,signal:u16)->bool{self.active_control().has_internal(signal)}
    fn latch_mar(&mut self,value:u16){if self.internal_enabled(internal::MAR_LOAD){self.mar=value;}} fn latch_mdr(&mut self,value:u8){if self.internal_enabled(internal::MDR_LOAD){self.mdr=value;}} fn latch_ir(&mut self){if self.internal_enabled(internal::IR_LOAD){self.ir=self.mdr;}} fn latch_operand_a(&mut self,value:u8){if self.internal_enabled(internal::OPERAND_A_LOAD){self.alu_a=value;}} fn latch_operand_b(&mut self,value:u8){if self.internal_enabled(internal::OPERAND_B_LOAD){self.alu_b=value;}} fn latch_alu_op(&mut self,operation:AluOp){if self.internal_enabled(internal::ALU_OP_LOAD){self.alu_op=Some(operation);}}
    fn latch_register_select(&mut self,reg:Reg){let control=self.active_control();if !control.has_internal(internal::REG_SELECT){return;}let value=self.regs[reg as usize];if control.has_internal(internal::OPERAND_A_LOAD){self.reg_a=Some(reg);self.alu_a=value;}if control.has_internal(internal::OPERAND_B_LOAD){self.reg_b=Some(reg);self.alu_b=value;}}
    fn latch_register_select_traced<B:Bus>(&mut self,bus:&mut B,pc:u16,reg:Reg,control:&'static str){let enabled=self.internal_enabled(internal::REG_SELECT);self.latch_register_select(reg);if enabled{bus.trace_control_latch(pc,ControlLatchKind::RegSelect,u16::from(reg.code()),true,control);}}
    fn latch_address_lo(&mut self,value:u8){if self.internal_enabled(internal::ADDR_LO_LOAD){self.address_lo=value;}} fn latch_address_hi(&mut self,value:u8){if self.internal_enabled(internal::ADDR_HI_LOAD){self.address_hi=value;}} fn latch_condition(&mut self,value:bool){if self.internal_enabled(internal::CONDITION_LOAD){self.condition_latch=value;}} fn address_latch(&self)->u16{u16::from_le_bytes([self.address_lo,self.address_hi])}
    fn latch_address_lo_traced<B:Bus>(&mut self,bus:&mut B,pc:u16,value:u8,control:&'static str){let enabled=self.internal_enabled(internal::ADDR_LO_LOAD);self.latch_address_lo(value);if enabled{bus.trace_control_latch(pc,ControlLatchKind::AddressLo,u16::from(self.address_lo),true,control);}}
    fn latch_address_hi_traced<B:Bus>(&mut self,bus:&mut B,pc:u16,value:u8,control:&'static str){let enabled=self.internal_enabled(internal::ADDR_HI_LOAD);self.latch_address_hi(value);if enabled{bus.trace_control_latch(pc,ControlLatchKind::AddressHi,u16::from(self.address_hi),true,control);}}
    fn latch_condition_traced<B:Bus>(&mut self,bus:&mut B,pc:u16,value:bool,control:&'static str){let enabled=self.internal_enabled(internal::CONDITION_LOAD);self.latch_condition(value);if enabled{bus.trace_control_latch(pc,ControlLatchKind::Condition,u16::from(self.condition_latch),true,control);}}
    fn select_pc_target(&mut self,target:Option<u16>){if self.internal_enabled(internal::PC_SELECT){self.pc_selected=target;}} fn select_pc_target_traced<B:Bus>(&mut self,bus:&mut B,pc:u16,target:Option<u16>,control:&'static str){let enabled=self.internal_enabled(internal::PC_SELECT);self.select_pc_target(target);if enabled{bus.trace_control_latch(pc,ControlLatchKind::PcSelect,self.pc_selected.unwrap_or(0),self.pc_selected.is_some(),control);}} fn commit_selected_pc<B:Bus>(&mut self,bus:&mut B,source:PcSource,control:&'static str){let word=self.active_control();if !word.pc_load||!word.has_internal(internal::ARCH_COMMIT){return;}let Some(target)=self.pc_selected else{return;};let before=self.pc;self.pc=target;bus.trace_pc_load(before,target,source,control);}
    fn latched_alu_trace(&self)->Option<AluTrace>{let operation=self.alu_op?;Some(match operation{AluOp::Pass=>logic_trace(operation,self.alu_b,0,self.alu_b),AluOp::Add=>ripple_add(self.alu_a,self.alu_b,false,operation),AluOp::Sub|AluOp::Compare=>ripple_sub(self.alu_a,self.alu_b,operation),AluOp::And=>logic_trace(operation,self.alu_a,self.alu_b,self.alu_a&self.alu_b),AluOp::Or=>logic_trace(operation,self.alu_a,self.alu_b,self.alu_a|self.alu_b),AluOp::Xor=>logic_trace(operation,self.alu_a,self.alu_b,self.alu_a^self.alu_b)})}
    fn propagate_latched_alu<B:Bus>(&mut self,bus:&mut B,pc:u16,control:&'static str,compare:bool)->Option<AluTrace>{if !self.active_control().alu_enable{return None;}let trace=self.latched_alu_trace()?;if compare{self.latch_compare_flags(trace);}else if trace.op==AluOp::Pass||matches!(trace.op,AluOp::And|AluOp::Or|AluOp::Xor){self.latch_flags(Flags{zero:trace.result==0,carry:false,less:false});}else{self.latch_arithmetic_flags(trace);}if self.internal_enabled(internal::FLAGS_LOAD){bus.trace_flags(pc,self.flags,control);}bus.trace_alu_exact(pc,trace,control);Some(trace)}
    fn latch_flags(&mut self,value:Flags){if self.internal_enabled(internal::FLAGS_LOAD){self.flags=value;}} fn increment_pc_controlled<B:Bus>(&mut self,bus:&mut B){if !self.internal_enabled(internal::PC_INC){return;}let increment=ripple_increment16(self.pc);self.pc=increment.after;bus.trace_pc_increment(increment);} fn read_bus_enabled(&self)->bool{let control=self.active_control();control.mem_read&&control.has_internal(internal::MDR_LOAD)&&control.has_internal(internal::BUS_DATA_ENABLE)} fn write_bus_commit_enabled(&self)->bool{let control=self.active_control();control.mem_write&&control.has_internal(internal::BUS_ADDRESS_ENABLE)&&control.has_internal(internal::BUS_DATA_ENABLE)&&control.has_internal(internal::ARCH_COMMIT)}

    fn fetch_opcode<B:Bus>(&mut self,bus:&mut B)->u8{let t=self.micro.fetch_start();self.publish_microaddress(bus,t,"FETCH_ADDR");self.latch_mar(self.pc);self.emit_cycle(bus,MicroPhase::T0,MicroCycleKind::FetchAddress,"FETCH_ADDR");let t=self.micro.advance();self.publish_microaddress(bus,t,"FETCH_DATA");if self.read_bus_enabled(){let value=bus.fetch8(self.mar);self.latch_mdr(value);}self.increment_pc_controlled(bus);self.emit_cycle(bus,MicroPhase::T1,MicroCycleKind::FetchData,"FETCH_DATA");let t=self.micro.advance();self.publish_microaddress(bus,t,"IR_LATCH");self.latch_ir();self.emit_cycle(bus,MicroPhase::T2,MicroCycleKind::DecodeLatch,"IR_LATCH");self.ir}
    fn next8<B:Bus>(&mut self,bus:&mut B)->u8{let t=self.micro.call(uaddr::OPERAND_T0);self.publish_microaddress(bus,t,"OPERAND_ADDR");self.latch_mar(self.pc);self.emit_cycle(bus,MicroPhase::T0,MicroCycleKind::OperandAddress,"OPERAND_ADDR");let t=self.micro.advance();self.publish_microaddress(bus,t,"OPERAND_DATA");if self.read_bus_enabled(){let value=bus.fetch8(self.mar);self.latch_mdr(value);}self.increment_pc_controlled(bus);self.emit_cycle(bus,MicroPhase::T1,MicroCycleKind::OperandData,"OPERAND_DATA");let t=self.micro.advance();self.publish_microaddress(bus,t,"OPERAND_READY");self.emit_cycle(bus,MicroPhase::T2,MicroCycleKind::OperandReady,"OPERAND_READY");let value=self.mdr;let t=self.micro.return_from_routine();self.publish_microaddress(bus,t,"EXEC_RETURN");value}
    fn next_reg<B:Bus>(&mut self,bus:&mut B)->Option<Reg>{Reg::from_code(self.next8(bus))}
    fn read_memory<B:Bus>(&mut self,bus:&mut B,pc:u16,address:u16,control:&'static str)->u8{let t=self.micro.call(uaddr::READ_T0);self.publish_microaddress(bus,t,control);self.latch_mar(address);self.emit_cycle(bus,MicroPhase::T0,MicroCycleKind::MemoryAddress,control);let t=self.micro.advance();self.publish_microaddress(bus,t,control);if self.read_bus_enabled(){let value=bus.read8(pc,self.mar);self.latch_mdr(value);}self.emit_cycle(bus,MicroPhase::T1,MicroCycleKind::MemoryRead,control);let t=self.micro.advance();self.publish_microaddress(bus,t,control);self.emit_cycle(bus,MicroPhase::T2,MicroCycleKind::OperandReady,control);let value=self.mdr;let t=self.micro.return_from_routine();self.publish_microaddress(bus,t,"EXEC_RETURN");value}
    fn write_memory<B:Bus>(&mut self,bus:&mut B,pc:u16,address:u16,value:u8,control:&'static str){let t=self.micro.call(uaddr::WRITE_T0);self.publish_microaddress(bus,t,control);self.latch_mar(address);self.emit_cycle(bus,MicroPhase::T0,MicroCycleKind::MemoryAddress,control);let t=self.micro.advance();self.publish_microaddress(bus,t,control);self.latch_mdr(value);self.emit_cycle(bus,MicroPhase::T1,MicroCycleKind::MemoryWriteData,control);let t=self.micro.advance();self.publish_microaddress(bus,t,control);if self.write_bus_commit_enabled(){bus.write8(pc,self.mar,self.mdr);}self.emit_cycle(bus,MicroPhase::T2,MicroCycleKind::MemoryWriteCommit,control);let t=self.micro.return_from_routine();self.publish_microaddress(bus,t,"EXEC_RETURN");}
    fn advance_execute<B:Bus>(&mut self,bus:&mut B,label:&'static str){let t=self.micro.advance();self.publish_microaddress(bus,t,label)} fn publish_microaddress<B:Bus>(&self,bus:&mut B,t:MicroAddressTransition,label:&'static str){let word=control_word_at(t.after,self.ir);bus.trace_microaddress(t,self.ir,word.bits24(),label)} fn emit_cycle<B:Bus>(&mut self,bus:&mut B,phase:MicroPhase,kind:MicroCycleKind,control:&'static str){self.phase=phase;bus.trace_microcycle(phase,kind,self.pc,self.mar,self.mdr,self.ir,control)}
    fn write_reg<B:Bus>(&mut self,bus:&mut B,pc:u16,reg:Reg,value:u8,control:&'static str){if !self.active_control().reg_write{return;}let slot=&mut self.regs[reg as usize];let before=*slot;*slot=value;bus.trace_register_write(pc,reg,before,value,control)} fn write_selected_a<B:Bus>(&mut self,bus:&mut B,pc:u16,value:u8,control:&'static str)->bool{let Some(reg)=self.reg_a else{return false;};self.write_reg(bus,pc,reg,value,control);true}

    fn load_memory<B:Bus>(&mut self,bus:&mut B,pc:u16,opcode:u8,control:&'static str)->StepOutcome{let Some(reg)=self.next_reg(bus)else{return self.fault(pc,opcode);};self.latch_register_select_traced(bus,pc,reg,control);self.advance_execute(bus,"LD_ADDR_LO");let lo=self.next8(bus);self.latch_address_lo_traced(bus,pc,lo,control);self.advance_execute(bus,"LD_ADDR_HI");let hi=self.next8(bus);self.latch_address_hi_traced(bus,pc,hi,control);self.advance_execute(bus,"LD_READ");let value=self.read_memory(bus,pc,self.address_latch(),"LD");self.advance_execute(bus,"LD_COMMIT");if !self.write_selected_a(bus,pc,value,control){return self.fault(pc,opcode);}self.latch_flags(Flags{zero:value==0,carry:self.flags.carry,less:false});if self.internal_enabled(internal::FLAGS_LOAD){bus.trace_flags(pc,self.flags,control);}StepOutcome::Continue}
    fn store_memory<B:Bus>(&mut self,bus:&mut B,pc:u16,opcode:u8)->StepOutcome{let control="ST";let lo=self.next8(bus);self.latch_address_lo_traced(bus,pc,lo,control);self.advance_execute(bus,"ST_ADDR_HI");let hi=self.next8(bus);self.latch_address_hi_traced(bus,pc,hi,control);self.advance_execute(bus,"ST_SOURCE");let Some(reg)=self.next_reg(bus)else{return self.fault(pc,opcode);};self.latch_register_select_traced(bus,pc,reg,control);let value=self.alu_a;self.advance_execute(bus,"ST_WRITE");self.write_memory(bus,pc,self.address_latch(),value,"ST");self.advance_execute(bus,"ST_COMMIT");StepOutcome::Continue}
    fn control_transfer<B:Bus>(&mut self,bus:&mut B,pc:u16,condition:bool,source:PcSource,control:&'static str)->StepOutcome{let lo=self.next8(bus);self.latch_address_lo_traced(bus,pc,lo,control);self.advance_execute(bus,"TARGET_HI");let hi=self.next8(bus);self.latch_address_hi_traced(bus,pc,hi,control);self.advance_execute(bus,"BRANCH_CONDITION");self.latch_condition_traced(bus,pc,condition,control);self.advance_execute(bus,"PC_SELECT");let selected=self.condition_latch.then_some(self.address_latch());self.select_pc_target_traced(bus,pc,selected,control);self.advance_execute(bus,"PC_COMMIT");self.commit_selected_pc(bus,source,control);bus.trace_control(pc,control);StepOutcome::Continue}
    fn call_subroutine<B:Bus>(&mut self,bus:&mut B,pc:u16,control:&'static str)->StepOutcome{let lo=self.next8(bus);self.latch_address_lo_traced(bus,pc,lo,control);self.advance_execute(bus,"CALL_TARGET_HI");let hi=self.next8(bus);self.latch_address_hi_traced(bus,pc,hi,control);let ret=self.pc;self.advance_execute(bus,"CALL_PUSH_HI");self.push(bus,pc,(ret>>8)as u8);self.advance_execute(bus,"CALL_PUSH_LO");self.push(bus,pc,ret as u8);self.advance_execute(bus,"CALL_PC_COMMIT");self.select_pc_target_traced(bus,pc,Some(self.address_latch()),control);self.commit_selected_pc(bus,PcSource::Call,control);bus.trace_control(pc,control);StepOutcome::Continue}
    fn return_subroutine<B:Bus>(&mut self,bus:&mut B,pc:u16,control:&'static str)->StepOutcome{let lo=self.pop(bus,pc);self.latch_address_lo_traced(bus,pc,lo,control);self.advance_execute(bus,"RET_POP_HI");let hi=self.pop(bus,pc);self.latch_address_hi_traced(bus,pc,hi,control);self.advance_execute(bus,"RET_TARGET");self.advance_execute(bus,"RET_PC_SELECT");self.select_pc_target_traced(bus,pc,Some(self.address_latch()),control);self.advance_execute(bus,"RET_PC_COMMIT");self.commit_selected_pc(bus,PcSource::Return,control);bus.trace_control(pc,control);StepOutcome::Continue}
    fn binary_register_alu<B:Bus>(&mut self,bus:&mut B,pc:u16,opcode:u8,operation:AluOp,control:&'static str,compare:bool)->StepOutcome{let Some(lhs_reg)=self.next_reg(bus)else{return self.fault(pc,opcode);};self.latch_register_select_traced(bus,pc,lhs_reg,control);self.advance_execute(bus,"ALU_OPERAND_B");let Some(rhs_reg)=self.next_reg(bus)else{return self.fault(pc,opcode);};self.latch_register_select_traced(bus,pc,rhs_reg,control);self.advance_execute(bus,"ALU_SELECT");self.latch_alu_op(operation);self.advance_execute(bus,"ALU_PROPAGATE");let Some(trace)=self.propagate_latched_alu(bus,pc,control,compare)else{return self.fault(pc,opcode);};self.advance_execute(bus,"ALU_COMMIT");if !compare&&!self.write_selected_a(bus,pc,trace.result,control){return self.fault(pc,opcode);}StepOutcome::Continue}
    fn immediate_arithmetic<B:Bus>(&mut self,bus:&mut B,pc:u16,opcode:u8,operation:AluOp,control:&'static str)->StepOutcome{let Some(reg)=self.next_reg(bus)else{return self.fault(pc,opcode);};self.latch_register_select_traced(bus,pc,reg,control);if opcode==op::ADDI{self.advance_execute(bus,"ADDI_VALUE");let rhs=self.next8(bus);self.latch_operand_b(rhs);self.latch_alu_op(operation);self.advance_execute(bus,"ADDI_COMMIT");let Some(trace)=self.propagate_latched_alu(bus,pc,control,false)else{return self.fault(pc,opcode);};if !self.write_selected_a(bus,pc,trace.result,control){return self.fault(pc,opcode);}return StepOutcome::Continue;}self.advance_execute(bus,"ALU_OPERAND_B");let rhs=self.next8(bus);self.latch_operand_b(rhs);self.advance_execute(bus,"ALU_SELECT");self.latch_alu_op(operation);self.advance_execute(bus,"ALU_PROPAGATE");let Some(trace)=self.propagate_latched_alu(bus,pc,control,false)else{return self.fault(pc,opcode);};self.advance_execute(bus,"ALU_COMMIT");if !self.write_selected_a(bus,pc,trace.result,control){return self.fault(pc,opcode);}StepOutcome::Continue}
    fn immediate_logic<B:Bus>(&mut self,bus:&mut B,pc:u16,opcode:u8,operation:AluOp,control:&'static str)->StepOutcome{let Some(reg)=self.next_reg(bus)else{return self.fault(pc,opcode);};self.latch_register_select_traced(bus,pc,reg,control);self.advance_execute(bus,"ALU_OPERAND_B");let rhs=self.next8(bus);self.latch_operand_b(rhs);self.advance_execute(bus,"ALU_SELECT");self.latch_alu_op(operation);self.advance_execute(bus,"ALU_PROPAGATE");let Some(trace)=self.propagate_latched_alu(bus,pc,control,false)else{return self.fault(pc,opcode);};self.advance_execute(bus,"ALU_COMMIT");if !self.write_selected_a(bus,pc,trace.result,control){return self.fault(pc,opcode);}StepOutcome::Continue}
    fn unary_arithmetic<B:Bus>(&mut self,bus:&mut B,pc:u16,opcode:u8,increment:bool)->StepOutcome{let control=if increment{"INC"}else{"DEC"};let Some(reg)=self.next_reg(bus)else{return self.fault(pc,opcode);};self.latch_register_select_traced(bus,pc,reg,control);self.advance_execute(bus,"ALU_CONST_ONE");self.latch_operand_b(1);self.advance_execute(bus,"ALU_SELECT");let operation=if increment{AluOp::Add}else{AluOp::Sub};self.latch_alu_op(operation);self.advance_execute(bus,"ALU_PROPAGATE");let Some(trace)=self.propagate_latched_alu(bus,pc,control,false)else{return self.fault(pc,opcode);};self.advance_execute(bus,"ALU_COMMIT");if !self.write_selected_a(bus,pc,trace.result,control){return self.fault(pc,opcode);}StepOutcome::Continue}
    fn compare_immediate<B:Bus>(&mut self,bus:&mut B,pc:u16,opcode:u8,control:&'static str)->StepOutcome{let Some(reg)=self.next_reg(bus)else{return self.fault(pc,opcode);};self.latch_register_select_traced(bus,pc,reg,control);self.advance_execute(bus,"ALU_OPERAND_B");let rhs=self.next8(bus);self.latch_operand_b(rhs);self.advance_execute(bus,"ALU_SELECT");self.latch_alu_op(AluOp::Compare);self.advance_execute(bus,"ALU_PROPAGATE");let Some(_trace)=self.propagate_latched_alu(bus,pc,control,true)else{return self.fault(pc,opcode);};self.advance_execute(bus,"ALU_COMMIT");StepOutcome::Continue}
    fn latch_arithmetic_flags(&mut self,trace:AluTrace){self.latch_flags(Flags{zero:trace.result==0,carry:trace.final_carry(),less:!trace.final_carry()&&matches!(trace.op,AluOp::Sub)})} fn latch_compare_flags(&mut self,trace:AluTrace){self.latch_flags(Flags{zero:trace.result==0,carry:trace.final_carry(),less:!trace.final_carry()})}
    fn push<B:Bus>(&mut self,bus:&mut B,pc:u16,value:u8){if !self.active_control().stack_enable{return;}self.sp=ripple_decrement16(self.sp).after;self.write_memory(bus,pc,self.sp,value,"STACK_PUSH")} fn pop<B:Bus>(&mut self,bus:&mut B,pc:u16)->u8{if !self.active_control().stack_enable{return 0;}let value=self.read_memory(bus,pc,self.sp,"STACK_POP");self.sp=ripple_increment16(self.sp).after;value} fn fault(&mut self,pc:u16,opcode:u8)->StepOutcome{self.halted=true;StepOutcome::Fault{pc,opcode}}
}

#[must_use]pub const fn mnemonic(value:u8)->&'static str{match decode_microcode(value){Some(instruction)=>instruction.mnemonic,None=>"FAULT"}} #[must_use]pub const fn phase_for_opcode(value:u8)->PhaseKind{match decode_microcode(value){Some(instruction)if instruction.control.mem_read=>PhaseKind::MemoryRead,Some(instruction)if instruction.control.mem_write=>PhaseKind::MemoryWrite,Some(instruction)if instruction.control.alu_enable=>PhaseKind::Alu,_=>PhaseKind::Decode}}

#[cfg(test)]mod tests{
use super::*;
struct TestBus{memory:Vec<u8>,exact_alu:Vec<AluTrace>,writes:Vec<(Reg,u8,u8)>,pc_increments:Vec<PcIncrementTrace>,pc_loads:Vec<(u16,u16,PcSource,&'static str)>,cycles:Vec<(MicroPhase,MicroCycleKind,u16,u16,u8,u8)>,micro_addresses:Vec<MicroAddressTransition>,micro_control_bits:Vec<u32>}
impl Default for TestBus{fn default()->Self{Self{memory:vec![0;65536],exact_alu:vec![],writes:vec![],pc_increments:vec![],pc_loads:vec![],cycles:vec![],micro_addresses:vec![],micro_control_bits:vec![]}}}
impl Bus for TestBus{fn fetch8(&mut self,pc:u16)->u8{self.memory[pc as usize]}fn read8(&mut self,_pc:u16,address:u16)->u8{self.memory[address as usize]}fn write8(&mut self,_pc:u16,address:u16,value:u8){self.memory[address as usize]=value}fn trace_decode(&mut self,_pc:u16,_opcode:u8,_mnemonic:&'static str){}fn trace_alu(&mut self,_pc:u16,_value:u8,_control:&'static str){}fn trace_control(&mut self,_pc:u16,_control:&'static str){}fn trace_alu_exact(&mut self,_pc:u16,trace:AluTrace,_control:&'static str){self.exact_alu.push(trace)}fn trace_register_write(&mut self,_pc:u16,reg:Reg,before:u8,after:u8,_control:&'static str){self.writes.push((reg,before,after))}fn trace_pc_increment(&mut self,trace:PcIncrementTrace){self.pc_increments.push(trace)}fn trace_pc_load(&mut self,before:u16,after:u16,source:PcSource,control:&'static str){self.pc_loads.push((before,after,source,control))}fn trace_microaddress(&mut self,t:MicroAddressTransition,_opcode:u8,bits:u32,_label:&'static str){self.micro_addresses.push(t);self.micro_control_bits.push(bits)}fn trace_microcycle(&mut self,p:MicroPhase,k:MicroCycleKind,pc:u16,mar:u16,mdr:u8,ir:u8,_c:&'static str){self.cycles.push((p,k,pc,mar,mdr,ir))}}
fn assert_five_execute_rows(cpu:&Cpu,bus:&TestBus,opcode:u8){let base=execute_address(opcode).unwrap();for step in 0..5{assert!(bus.micro_addresses.iter().any(|t|t.after==base+step),"missing opcode {opcode:02X} execute row {step}");}assert_eq!(cpu.micro_address(),base+4);}
#[test]fn microaddress_trace_carries_internal_control_bits(){let mut bus=TestBus::default();bus.memory[0]=op::NOP;let mut cpu=Cpu::default();assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert!(bus.micro_control_bits.iter().any(|bits|*bits>u32::from(u8::MAX)));}
#[test]fn internal_fetch_enables_gate_latches_and_pc_increment(){let mut bus=TestBus::default();let mut cpu=Cpu::default();cpu.ir=op::NOP;cpu.pc=0x00FF;cpu.mar=0xAAAA;cpu.mdr=0x11;cpu.micro.dispatch(uaddr::FETCH_T1);cpu.latch_mar(0x00FF);assert_eq!(cpu.mar,0xAAAA);cpu.micro.dispatch(uaddr::FETCH_T0);cpu.latch_mar(0x00FF);assert_eq!(cpu.mar,0x00FF);cpu.latch_mdr(0x22);assert_eq!(cpu.mdr,0x11);cpu.micro.dispatch(uaddr::FETCH_T1);cpu.latch_mdr(0x22);assert_eq!(cpu.mdr,0x22);cpu.ir=op::NOP;cpu.latch_ir();assert_eq!(cpu.ir,op::NOP);cpu.micro.dispatch(uaddr::FETCH_T2);cpu.latch_ir();assert_eq!(cpu.ir,0x22);cpu.ir=op::NOP;cpu.micro.dispatch(uaddr::FETCH_T0);cpu.increment_pc_controlled(&mut bus);assert_eq!(cpu.pc,0x00FF);cpu.micro.dispatch(uaddr::FETCH_T1);cpu.increment_pc_controlled(&mut bus);assert_eq!(cpu.pc,0x0100);assert!(bus.pc_increments.last().unwrap().low_byte_carry());}
#[test]fn shared_routines_require_internal_bus_and_latch_enables(){let mut cpu=Cpu::default();cpu.ir=op::NOP;cpu.mar=0x1111;cpu.mdr=0x22;cpu.micro.dispatch(uaddr::OPERAND_T0);cpu.latch_mar(0x3333);assert_eq!(cpu.mar,0x3333);assert!(!cpu.read_bus_enabled());cpu.micro.dispatch(uaddr::OPERAND_T1);assert!(cpu.read_bus_enabled());cpu.latch_mdr(0x44);assert_eq!(cpu.mdr,0x44);cpu.micro.dispatch(uaddr::WRITE_T1);assert!(!cpu.write_bus_commit_enabled());cpu.micro.dispatch(uaddr::WRITE_T2);assert!(cpu.write_bus_commit_enabled());}
#[test]fn flags_latch_requires_flags_load_on_selected_row(){let mut cpu=Cpu::default();cpu.ir=op::ADD;let base=execute_address(op::ADD).unwrap();cpu.micro.dispatch(base+2);cpu.latch_flags(Flags{zero:true,carry:true,less:true});assert_eq!(cpu.flags,Flags::default());cpu.micro.dispatch(base+3);cpu.latch_flags(Flags{zero:true,carry:true,less:false});assert_eq!(cpu.flags,Flags{zero:true,carry:true,less:false});cpu.ir=op::LDI;let ldi=execute_address(op::LDI).unwrap();cpu.flags=Flags::default();cpu.micro.dispatch(ldi+2);cpu.latch_flags(Flags{zero:true,carry:false,less:false});assert!(cpu.flags.zero);}
#[test]fn alu_operand_and_operation_latches_require_their_physical_rows(){let mut cpu=Cpu::default();cpu.ir=op::ADD;let base=execute_address(op::ADD).unwrap();cpu.micro.dispatch(base+1);cpu.latch_operand_a(0x12);assert_eq!(cpu.alu_a,0);cpu.micro.dispatch(base);cpu.latch_operand_a(0x12);assert_eq!(cpu.alu_a,0x12);cpu.micro.dispatch(base+2);cpu.latch_operand_b(0x34);assert_eq!(cpu.alu_b,0);cpu.micro.dispatch(base+1);cpu.latch_operand_b(0x34);assert_eq!(cpu.alu_b,0x34);cpu.micro.dispatch(base+3);cpu.latch_alu_op(AluOp::Add);assert_eq!(cpu.alu_op,None);cpu.micro.dispatch(base+2);cpu.latch_alu_op(AluOp::Add);assert_eq!(cpu.alu_op,Some(AluOp::Add));cpu.micro.dispatch(base+3);assert_eq!(cpu.latched_alu_trace().unwrap().result,0x46);}
#[test]fn register_select_requires_reg_select_and_drives_operand_latches(){let mut cpu=Cpu::default();cpu.ir=op::ADD;cpu.regs[Reg::A as usize]=3;cpu.regs[Reg::B as usize]=9;let base=execute_address(op::ADD).unwrap();cpu.micro.dispatch(base+2);cpu.latch_register_select(Reg::A);assert_eq!(cpu.reg_a,None);cpu.micro.dispatch(base);cpu.latch_register_select(Reg::A);assert_eq!(cpu.reg_a,Some(Reg::A));assert_eq!(cpu.alu_a,3);cpu.micro.dispatch(base+1);cpu.latch_register_select(Reg::B);assert_eq!(cpu.reg_b,Some(Reg::B));assert_eq!(cpu.alu_b,9);}
#[test]fn selected_register_latch_is_the_writeback_destination(){let mut bus=TestBus::default();let mut cpu=Cpu::default();cpu.ir=op::ADD;cpu.regs[Reg::A as usize]=1;cpu.regs[Reg::B as usize]=7;let base=execute_address(op::ADD).unwrap();cpu.micro.dispatch(base);cpu.latch_register_select(Reg::B);cpu.micro.dispatch(base+4);assert!(cpu.write_selected_a(&mut bus,0,42,"ADD"));assert_eq!(cpu.reg(Reg::A),1);assert_eq!(cpu.reg(Reg::B),42);assert_eq!(bus.writes.last().unwrap().0,Reg::B);}
#[test]fn selected_alu_operation_is_not_the_callers_local_operation_after_latching(){let mut cpu=Cpu::default();cpu.ir=op::ADD;let base=execute_address(op::ADD).unwrap();cpu.micro.dispatch(base);cpu.latch_operand_a(9);cpu.micro.dispatch(base+1);cpu.latch_operand_b(4);cpu.micro.dispatch(base+2);cpu.latch_alu_op(AluOp::Sub);cpu.micro.dispatch(base+3);assert_eq!(cpu.latched_alu_trace().unwrap().result,5);cpu.micro.dispatch(base+2);cpu.latch_alu_op(AluOp::Add);cpu.micro.dispatch(base+3);assert_eq!(cpu.latched_alu_trace().unwrap().result,13);}
#[test]fn address_condition_and_pc_selection_require_their_physical_rows(){let mut bus=TestBus::default();let mut cpu=Cpu::default();cpu.ir=op::JZ;let base=execute_address(op::JZ).unwrap();cpu.address_lo=0xAA;cpu.address_hi=0xBB;cpu.micro.dispatch(base+1);cpu.latch_address_lo(0x34);assert_eq!(cpu.address_lo,0xAA);cpu.micro.dispatch(base);cpu.latch_address_lo(0x34);assert_eq!(cpu.address_lo,0x34);cpu.micro.dispatch(base);cpu.latch_address_hi(0x12);assert_eq!(cpu.address_hi,0xBB);cpu.micro.dispatch(base+1);cpu.latch_address_hi(0x12);assert_eq!(cpu.address_latch(),0x1234);cpu.micro.dispatch(base+1);cpu.latch_condition(true);assert!(!cpu.condition_latch);cpu.micro.dispatch(base+2);cpu.latch_condition(true);assert!(cpu.condition_latch);cpu.micro.dispatch(base+2);cpu.select_pc_target(Some(cpu.address_latch()));assert_eq!(cpu.pc_selected,None);cpu.micro.dispatch(base+3);cpu.select_pc_target(Some(cpu.address_latch()));assert_eq!(cpu.pc_selected,Some(0x1234));cpu.pc=7;cpu.commit_selected_pc(&mut bus,PcSource::Branch,"JZ");assert_eq!(cpu.pc,7);cpu.micro.dispatch(base+4);cpu.commit_selected_pc(&mut bus,PcSource::Branch,"JZ");assert_eq!(cpu.pc,0x1234);assert_eq!(bus.pc_loads.len(),1);}
#[test]fn not_taken_branch_clears_stale_pc_selection(){let mut cpu=Cpu::default();cpu.ir=op::JZ;let base=execute_address(op::JZ).unwrap();cpu.pc_selected=Some(0xBEEF);cpu.address_lo=0x34;cpu.address_hi=0x12;cpu.condition_latch=false;cpu.micro.dispatch(base+3);cpu.select_pc_target(cpu.condition_latch.then_some(cpu.address_latch()));assert_eq!(cpu.pc_selected,None);}
#[test]fn control_rom_gates_register_pc_and_stack_effects(){let mut bus=TestBus::default();let mut cpu=Cpu::default();cpu.ir=op::ADD;cpu.regs[0]=7;cpu.micro.dispatch(execute_address(op::ADD).unwrap()+3);cpu.write_reg(&mut bus,0,Reg::A,9,"ADD");assert_eq!(cpu.reg(Reg::A),7);cpu.micro.dispatch(execute_address(op::ADD).unwrap()+4);cpu.write_reg(&mut bus,0,Reg::A,9,"ADD");assert_eq!(cpu.reg(Reg::A),9);cpu.ir=op::JMP;cpu.pc=3;let jump=execute_address(op::JMP).unwrap();cpu.micro.dispatch(jump+2);cpu.select_pc_target(Some(9));assert_eq!(cpu.pc_selected,None);cpu.micro.dispatch(jump+3);cpu.select_pc_target(Some(9));assert_eq!(cpu.pc_selected,Some(9));cpu.commit_selected_pc(&mut bus,PcSource::Jump,"JMP");assert_eq!(cpu.pc(),3);cpu.micro.dispatch(jump+4);cpu.commit_selected_pc(&mut bus,PcSource::Jump,"JMP");assert_eq!(cpu.pc(),9);cpu.ir=op::CALL;let initial=cpu.sp();cpu.micro.dispatch(execute_address(op::CALL).unwrap()+1);cpu.push(&mut bus,0,0xAA);assert_eq!(cpu.sp(),initial);cpu.micro.dispatch(execute_address(op::CALL).unwrap()+2);cpu.push(&mut bus,0,0xAA);assert_eq!(cpu.sp(),initial.wrapping_sub(1));}
#[test]fn compact_ldi_addi_use_authoritative_operand_op_and_register_latches(){let mut bus=TestBus::default();bus.memory[..7].copy_from_slice(&[op::LDI,0,4,op::ADDI,0,6,op::HALT]);let mut cpu=Cpu::default();assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert_eq!(cpu.reg_a,Some(Reg::A));assert_eq!(cpu.alu_a,0);assert_eq!(cpu.alu_b,4);assert_eq!(cpu.alu_op,Some(AluOp::Pass));assert_eq!(cpu.reg(Reg::A),4);bus.micro_addresses.clear();assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert_eq!(cpu.reg_a,Some(Reg::A));assert_eq!(cpu.alu_a,4);assert_eq!(cpu.alu_b,6);assert_eq!(cpu.alu_op,Some(AluOp::Add));assert_eq!(cpu.reg(Reg::A),10);assert_eq!(bus.exact_alu.last().unwrap().result,10);}
#[test]fn ld_and_st_are_causal_five_row_programs_with_shared_memory_routines(){let mut bus=TestBus::default();let program=[op::LD,0,0x80,0,op::ST,0x81,0,0,op::HALT];bus.memory[..program.len()].copy_from_slice(&program);bus.memory[0x80]=0x5A;let mut cpu=Cpu::default();assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert_five_execute_rows(&cpu,&bus,op::LD);assert_eq!(cpu.reg_a,Some(Reg::A));assert_eq!(cpu.address_latch(),0x0080);assert_eq!(cpu.reg(Reg::A),0x5A);bus.micro_addresses.clear();assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert_five_execute_rows(&cpu,&bus,op::ST);assert_eq!(cpu.reg_a,Some(Reg::A));assert_eq!(cpu.address_latch(),0x0081);assert_eq!(bus.memory[0x81],0x5A);}
#[test]fn branches_and_jump_are_causal_five_row_programs(){for(opcode,flag,taken)in[(op::JMP,false,true),(op::JZ,false,false),(op::JZ,true,true)]{let mut bus=TestBus::default();bus.memory[..6].copy_from_slice(&[opcode,5,0,op::HALT,op::HALT,op::HALT]);let mut cpu=Cpu::default();cpu.flags.zero=flag;assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert_five_execute_rows(&cpu,&bus,opcode);assert_eq!(cpu.address_latch(),5);assert_eq!(cpu.pc(),if taken{5}else{3});assert_eq!(!bus.pc_loads.is_empty(),taken);assert_eq!(cpu.pc_selected.is_some(),taken);}}
#[test]fn call_and_ret_follow_five_causal_rows_and_shared_stack_routines(){let mut bus=TestBus::default();let program=[op::CALL,5,0,op::HALT,op::HALT,op::RET];bus.memory[..program.len()].copy_from_slice(&program);let mut cpu=Cpu::default();let initial=cpu.sp();assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert_five_execute_rows(&cpu,&bus,op::CALL);assert_eq!(cpu.address_latch(),5);assert_eq!(cpu.sp(),initial.wrapping_sub(2));assert_eq!(cpu.pc(),5);bus.micro_addresses.clear();assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert_five_execute_rows(&cpu,&bus,op::RET);assert_eq!(cpu.address_latch(),3);assert_eq!(cpu.sp(),initial);assert_eq!(cpu.pc(),3);}
#[test]fn alu_five_row_family_remains_causal(){for(opcode,lhs,rhs,expected)in[(op::MOV,0x12,0xA5,0xA5),(op::ADD,7,9,16),(op::SUBI,9,4,5),(op::ANDI,12,10,8),(op::ORI,12,3,15),(op::XORI,12,10,6)]{let mut bus=TestBus::default();let mut cpu=Cpu::default();cpu.regs[0]=lhs;if matches!(opcode,op::MOV|op::ADD){cpu.regs[1]=rhs;bus.memory[..3].copy_from_slice(&[opcode,0,1]);}else{bus.memory[..3].copy_from_slice(&[opcode,0,rhs]);}assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert_five_execute_rows(&cpu,&bus,opcode);assert_eq!(cpu.reg_a,Some(Reg::A));if matches!(opcode,op::MOV|op::ADD){assert_eq!(cpu.reg_b,Some(Reg::B));}assert_eq!(cpu.reg(Reg::A),expected);}}
#[test]fn compare_and_unary_five_row_family_remains_causal(){for(opcode,before,expected)in[(op::INC,4,5),(op::DEC,4,3)]{let mut bus=TestBus::default();bus.memory[..2].copy_from_slice(&[opcode,0]);let mut cpu=Cpu::default();cpu.regs[0]=before;assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert_five_execute_rows(&cpu,&bus,opcode);assert_eq!(cpu.reg(Reg::A),expected);}let mut bus=TestBus::default();bus.memory[..3].copy_from_slice(&[op::CMPI,0,9]);let mut cpu=Cpu::default();cpu.regs[0]=7;assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);assert_five_execute_rows(&cpu,&bus,op::CMPI);assert!(cpu.flags.less);}
#[test]fn fetch_pc_advance_is_the_exact_ripple_incrementer(){let mut bus=TestBus::default();bus.memory[0xFF]=op::NOP;let mut cpu=Cpu::default();cpu.pc=0xFF;assert_eq!(cpu.step(&mut bus),StepOutcome::Continue);let increment=bus.pc_increments.last().unwrap();assert_eq!(increment.after,0x100);assert!(increment.low_byte_carry());}
#[test]fn undefined_opcode_faults_because_control_rom_has_no_entry(){let mut bus=TestBus::default();bus.memory[0]=0xAA;let mut cpu=Cpu::default();assert_eq!(cpu.step(&mut bus),StepOutcome::Fault{pc:0,opcode:0xAA});}
}
