use crate::game::{Bot,GameState,InputState,Projectile,ALIEN_COLS,ALIEN_H,ALIEN_ROWS,ALIEN_W,PLAYER_Y,SCREEN_H,SCREEN_W};
use crate::rng::{hash_seed,DeterministicRng};
use crate::trace::{FrameState,KillEvent,MatchTrace,MicroSample,PhaseKind};
const RAM:u16=0x2000;const VRAM:usize=0x8000;const VRAM_BYTES:usize=128*96/8;
#[derive(Debug)]pub struct Machine{mem:Box<[u8;65536]>,pc:u16,ir:u8,ord:u16}
impl Default for Machine{fn default()->Self{Self{mem:Box::new([0;65536]),pc:0,ir:0,ord:0}}}
impl Machine{
 pub fn run_match(seed:&str,max_frames:u32)->MatchTrace{let h=hash_seed(seed);let mut rng=DeterministicRng::from_seed(h);let bot=Bot::seeded(&mut rng);let mut m=Self::default();let mut g=GameState::default();let mut tr=MatchTrace::new(seed.into(),h);m.sync(&g);let sum=m.render_vram(&g);tr.frames.push(FrameState::from_game(&g,m.pc,sum));while g.frame<max_frames&&!g.is_clear(){m.ord=0;let input=bot.decide(&g,&mut rng);m.frame(&mut g,input,&mut rng,&mut tr)}tr.finished=g.is_clear();tr.total_frames=g.frame;tr.final_score=g.score;tr.final_lives=g.lives;tr}
 fn frame(&mut self,g:&mut GameState,input:InputState,rng:&mut DeterministicRng,tr:&mut MatchTrace){self.routine(g.frame,0x10,"INPUT",tr);self.sample(g.frame,PhaseKind::Input,Some(0xA000),Some(encode_input(input)),"INPUT_LATCH",tr);self.move_player(g,input,tr);self.routine(g.frame,0x20,"FLEET",tr);self.move_fleet(g,tr);self.routine(g.frame,0x30,"PLAYER_SHOT",tr);self.player_shot(g,input,tr);self.collide(g,tr);self.routine(g.frame,0x40,"ENEMY_SHOT",tr);self.enemy_shot(g,rng,tr);g.frame+=1;self.write16(g.frame,RAM+0x18,g.frame as u16,"FRAME_WRITE",tr);self.routine(g.frame,0x60,"VIDEO_DMA",tr);let sum=self.render_vram(g);self.sample(g.frame,PhaseKind::Dma,Some(VRAM as u16),Some((sum&255)as u8),"DMA_BURST_1536_BYTES",tr);self.sample(g.frame,PhaseKind::Scanout,Some(VRAM as u16),None,"SCANOUT_128x96_1BPP",tr);self.sample(g.frame,PhaseKind::VBlank,Some(0x8000),None,"VBLANK_IRQ",tr);self.sync(g);tr.frames.push(FrameState::from_game(g,self.pc,sum))}
 fn routine(&mut self,f:u32,op:u8,name:&str,tr:&mut MatchTrace){self.ir=op;self.sample(f,PhaseKind::Fetch,Some(self.pc),Some(op),"ROM_FETCH",tr);self.pc=self.pc.wrapping_add(1);self.sample(f,PhaseKind::Decode,None,Some(op),name,tr)}
 fn move_player(&mut self,g:&mut GameState,i:InputState,tr:&mut MatchTrace){let old=self.read(g.frame,RAM,"PLAYER_X_READ",tr);let v=(i16::from(old)+i16::from(i.horizontal.clamp(-1,1))*2).clamp(6,SCREEN_W-7)as u8;self.alu(g.frame,v,"PLAYER_X_ADD",tr);g.player_x=i16::from(v);self.write(g.frame,RAM,v,"PLAYER_X_WRITE",tr)}
 fn move_fleet(&mut self,g:&mut GameState,tr:&mut MatchTrace){if g.frame%3!=0{return}let old=self.read(g.frame,RAM+1,"FLEET_X_READ",tr);let nx=i16::from(old)+i16::from(g.fleet_dir);let right=nx+(ALIEN_COLS as i16-1)*12+ALIEN_W;if nx<=3||right>=SCREEN_W-3{g.fleet_dir=-g.fleet_dir;g.fleet_y+=2;self.write(g.frame,RAM+2,g.fleet_y as u8,"FLEET_Y_WRITE",tr);self.write(g.frame,RAM+3,g.fleet_dir as u8,"FLEET_DIR_WRITE",tr)}else{g.fleet_x=nx;self.alu(g.frame,nx as u8,"FLEET_X_ADD",tr);self.write(g.frame,RAM+1,nx as u8,"FLEET_X_WRITE",tr)}let line=g.fleet_y+(ALIEN_ROWS as i16-1)*13+ALIEN_H;if line>=PLAYER_Y-8{g.fleet_y=10;g.lives=g.lives.saturating_sub(1).max(1);self.write(g.frame,RAM+2,10,"FLEET_RESET",tr)}}
 fn player_shot(&mut self,g:&mut GameState,i:InputState,tr:&mut MatchTrace){g.player_cooldown=g.player_cooldown.saturating_sub(1);if let Some(mut s)=g.player_shot{s.y-=3;self.alu(g.frame,s.y.max(0)as u8,"SHOT_Y_SUB",tr);if s.y<=4{g.player_shot=None;self.write(g.frame,RAM+6,0,"SHOT_CLEAR",tr)}else{g.player_shot=Some(s);self.write(g.frame,RAM+5,s.y as u8,"SHOT_Y_WRITE",tr)}}else if i.fire&&g.player_cooldown==0{let s=Projectile{x:g.player_x,y:PLAYER_Y-5};g.player_shot=Some(s);g.player_cooldown=6;self.write(g.frame,RAM+4,s.x as u8,"SHOT_X_WRITE",tr);self.write(g.frame,RAM+5,s.y as u8,"SHOT_Y_WRITE",tr);self.write(g.frame,RAM+6,1,"SHOT_ARM",tr)}}
 fn collide(&mut self,g:&mut GameState,tr:&mut MatchTrace){let Some(s)=g.player_shot else{return};for r in 0..ALIEN_ROWS{let mask=self.read(g.frame,RAM+0x10+r as u16,"ALIEN_ROW_READ",tr);for c in 0..ALIEN_COLS{if mask&(1<<c)==0{continue}let(x,y)=g.alien_origin(r,c);if s.x>=x&&s.x<x+ALIEN_W&&s.y>=y&&s.y<y+ALIEN_H+2{let nm=mask&!(1<<c);self.alu(g.frame,nm,"ALIEN_MASK_AND",tr);if g.clear_alien(r,c){self.write(g.frame,RAM+0x10+r as u16,nm,"ALIEN_ROW_WRITE",tr);self.write16(g.frame,RAM+0x0A,g.score,"SCORE_WRITE",tr);g.player_shot=None;self.write(g.frame,RAM+6,0,"SHOT_HIT_CLEAR",tr);tr.kills.push(KillEvent{frame:g.frame,row:r,col:c,score_after:g.score})}return}}}}
 fn enemy_shot(&mut self,g:&mut GameState,rng:&mut DeterministicRng,tr:&mut MatchTrace){g.enemy_cooldown=g.enemy_cooldown.saturating_sub(1);if let Some(mut s)=g.enemy_shot{s.y+=2;self.alu(g.frame,s.y as u8,"ENEMY_SHOT_Y_ADD",tr);let(l,r)=g.player_bounds();if s.y>=PLAYER_Y-2&&s.x>=l&&s.x<=r{g.lives=g.lives.saturating_sub(1).max(1);g.enemy_shot=None;self.write(g.frame,RAM+9,0,"ENEMY_SHOT_HIT",tr)}else if s.y>=SCREEN_H-4{g.enemy_shot=None;self.write(g.frame,RAM+9,0,"ENEMY_SHOT_CLEAR",tr)}else{g.enemy_shot=Some(s);self.write(g.frame,RAM+8,s.y as u8,"ENEMY_SHOT_Y_WRITE",tr)}}if g.enemy_shot.is_none()&&g.enemy_cooldown==0{let a=g.bottom_shooters();if!a.is_empty(){let q=a[rng.range_u32(a.len()as u32)as usize];let s=Projectile{x:q.2,y:q.3+1};g.enemy_shot=Some(s);g.enemy_cooldown=22+rng.range_u32(42)as u8;self.write(g.frame,RAM+7,s.x as u8,"ENEMY_SHOT_X_WRITE",tr);self.write(g.frame,RAM+8,s.y as u8,"ENEMY_SHOT_Y_WRITE",tr);self.write(g.frame,RAM+9,1,"ENEMY_SHOT_ARM",tr)}}}
 fn read(&mut self,f:u32,a:u16,c:&str,tr:&mut MatchTrace)->u8{let v=self.mem[a as usize];self.sample(f,PhaseKind::MemoryRead,Some(a),Some(v),c,tr);v}fn write(&mut self,f:u32,a:u16,v:u8,c:&str,tr:&mut MatchTrace){self.mem[a as usize]=v;self.sample(f,PhaseKind::MemoryWrite,Some(a),Some(v),c,tr)}fn write16(&mut self,f:u32,a:u16,v:u16,c:&str,tr:&mut MatchTrace){self.write(f,a,v as u8,c,tr);self.write(f,a+1,(v>>8)as u8,c,tr)}fn alu(&mut self,f:u32,v:u8,c:&str,tr:&mut MatchTrace){self.sample(f,PhaseKind::Alu,None,Some(v),c,tr)}
 fn sample(&mut self,f:u32,p:PhaseKind,a:Option<u16>,d:Option<u8>,c:&str,tr:&mut MatchTrace){tr.micro_samples.push(MicroSample{frame:f,ordinal:self.ord,phase:p,pc:self.pc,address:a,data:d,control:c.into()});self.ord=self.ord.saturating_add(1)}
 fn sync(&mut self,g:&GameState){self.mem[RAM as usize]=g.player_x as u8;self.mem[(RAM+1)as usize]=g.fleet_x as u8;self.mem[(RAM+2)as usize]=g.fleet_y as u8;self.mem[(RAM+3)as usize]=g.fleet_dir as u8;self.mem[(RAM+0x0A)as usize]=g.score as u8;self.mem[(RAM+0x0B)as usize]=(g.score>>8)as u8;self.mem[(RAM+0x0C)as usize]=g.lives;for r in 0..ALIEN_ROWS{self.mem[(RAM+0x10+r as u16)as usize]=g.alive_rows[r]}}
 fn render_vram(&mut self,g:&GameState)->u32{self.mem[VRAM..VRAM+VRAM_BYTES].fill(0);for r in 0..ALIEN_ROWS{for c in 0..ALIEN_COLS{if g.alien_alive(r,c){let(x,y)=g.alien_origin(r,c);draw_invader(&mut self.mem,x,y,(r+c)%2==0)}}}draw_player(&mut self.mem,g.player_x,PLAYER_Y);if let Some(s)=g.player_shot{draw_shot(&mut self.mem,s.x,s.y,4)}if let Some(s)=g.enemy_shot{draw_shot(&mut self.mem,s.x,s.y,3)}for x in 0..SCREEN_W{pixel(&mut self.mem,x,SCREEN_H-3)}let mut h=0x811c9dc5u32;for b in &self.mem[VRAM..VRAM+VRAM_BYTES]{h^=u32::from(*b);h=h.wrapping_mul(0x01000193)}h}
}
fn encode_input(i:InputState)->u8{let h=if i.horizontal<0{1}else if i.horizontal>0{2}else{0};h|if i.fire{4}else{0}}
fn pixel(m:&mut[u8;65536],x:i16,y:i16){if!(0..SCREEN_W).contains(&x)||!(0..SCREEN_H).contains(&y){return}let i=y as usize*SCREEN_W as usize+x as usize;m[VRAM+i/8]|=1<<(7-i%8)}fn draw_player(m:&mut[u8;65536],x:i16,y:i16){for d in-5..=5{pixel(m,x+d,y)}for d in-3..=3{pixel(m,x+d,y-1)}for d in 2..=4{pixel(m,x,y-d)}}fn draw_shot(m:&mut[u8;65536],x:i16,y:i16,h:i16){for d in 0..h{pixel(m,x,y+d)}}fn draw_invader(m:&mut[u8;65536],x:i16,y:i16,b:bool){let a=["00111100","01111110","11011011","11111111","00100100","01000010"];let z=["01100110","11111111","10111101","11111111","00100100","01011010"];let bm=if b{&z}else{&a};for(dy,row)in bm.iter().enumerate(){for(dx,v)in row.as_bytes().iter().enumerate(){if*v==b'1'{pixel(m,x+dx as i16,y+dy as i16)}}}}
#[cfg(test)]mod tests{use super::*;#[test]fn deterministic(){let a=Machine::run_match("same",5000);let b=Machine::run_match("same",5000);assert_eq!(a.kills,b.kills);assert_eq!(a.total_frames,b.total_frames)}#[test]fn bot_clears(){let t=Machine::run_match("ci-clear",5000);assert!(t.finished,"{} frames",t.total_frames);assert_eq!(t.final_score,320);assert_eq!(t.kills.len(),32)}}
