use std::fmt::Write;
use crate::game::{GameState,Projectile,ALIEN_ROWS};
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum PhaseKind{Fetch,Decode,Input,MemoryRead,Alu,MemoryWrite,Dma,Scanout,VBlank}
impl PhaseKind{pub const fn as_str(self)->&'static str{match self{Self::Fetch=>"fetch",Self::Decode=>"decode",Self::Input=>"input",Self::MemoryRead=>"memory_read",Self::Alu=>"alu",Self::MemoryWrite=>"memory_write",Self::Dma=>"dma",Self::Scanout=>"scanout",Self::VBlank=>"vblank"}}}
#[derive(Debug,Clone)]pub struct MicroSample{pub frame:u32,pub ordinal:u16,pub phase:PhaseKind,pub pc:u16,pub address:Option<u16>,pub data:Option<u8>,pub control:String}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub struct ProjectileSnapshot{pub x:i16,pub y:i16}impl From<Projectile> for ProjectileSnapshot{fn from(v:Projectile)->Self{Self{x:v.x,y:v.y}}}
#[derive(Debug,Clone)]pub struct FrameState{pub frame:u32,pub player_x:i16,pub fleet_x:i16,pub fleet_y:i16,pub fleet_dir:i8,pub player_shot:Option<ProjectileSnapshot>,pub enemy_shot:Option<ProjectileSnapshot>,pub alive_rows:[u8;ALIEN_ROWS],pub score:u16,pub lives:u8,pub pc:u16,pub vram_checksum:u32}
impl FrameState{pub fn from_game(g:&GameState,pc:u16,sum:u32)->Self{Self{frame:g.frame,player_x:g.player_x,fleet_x:g.fleet_x,fleet_y:g.fleet_y,fleet_dir:g.fleet_dir,player_shot:g.player_shot.map(Into::into),enemy_shot:g.enemy_shot.map(Into::into),alive_rows:g.alive_rows,score:g.score,lives:g.lives,pc,vram_checksum:sum}}}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub struct KillEvent{pub frame:u32,pub row:usize,pub col:usize,pub score_after:u16}
#[derive(Debug,Clone)]pub struct MatchTrace{pub seed:String,pub seed_hash:u64,pub frames:Vec<FrameState>,pub micro_samples:Vec<MicroSample>,pub kills:Vec<KillEvent>,pub finished:bool,pub total_frames:u32,pub final_score:u16,pub final_lives:u8}
impl MatchTrace{pub fn new(seed:String,seed_hash:u64)->Self{Self{seed,seed_hash,frames:vec![],micro_samples:vec![],kills:vec![],finished:false,total_frames:0,final_score:0,final_lives:0}}pub fn to_json(&self)->String{let mut o=String::new();let _=write!(o,"{{\n  \"seed\":\"{}\",\n  \"seed_hash\":\"{:016x}\",\n  \"finished\":{},\n  \"total_frames\":{},\n  \"final_score\":{},\n  \"final_lives\":{},\n  \"kills\":[",esc(&self.seed),self.seed_hash,self.finished,self.total_frames,self.final_score,self.final_lives);for(i,k)in self.kills.iter().enumerate(){if i>0{o.push(',')}let _=write!(o,"{{\"frame\":{},\"row\":{},\"col\":{},\"score_after\":{}}}",k.frame,k.row,k.col,k.score_after)}o.push_str("],\n  \"frames\":[");for(i,f)in self.frames.iter().enumerate(){if i>0{o.push(',')}let ps=proj(f.player_shot);let es=proj(f.enemy_shot);let _=write!(o,"{{\"frame\":{},\"player_x\":{},\"fleet_x\":{},\"fleet_y\":{},\"fleet_dir\":{},\"player_shot\":{},\"enemy_shot\":{},\"alive_rows\":[{},{},{},{}],\"score\":{},\"lives\":{},\"pc\":{},\"vram_checksum\":{}}}",f.frame,f.player_x,f.fleet_x,f.fleet_y,f.fleet_dir,ps,es,f.alive_rows[0],f.alive_rows[1],f.alive_rows[2],f.alive_rows[3],f.score,f.lives,f.pc,f.vram_checksum)}o.push_str("],\n  \"micro_samples\":[");for(i,s)in self.micro_samples.iter().enumerate(){if i>0{o.push(',')}let a=s.address.map_or("null".into(),|v|v.to_string());let d=s.data.map_or("null".into(),|v|v.to_string());let _=write!(o,"{{\"frame\":{},\"ordinal\":{},\"phase\":\"{}\",\"pc\":{},\"address\":{},\"data\":{},\"control\":\"{}\"}}",s.frame,s.ordinal,s.phase.as_str(),s.pc,a,d,esc(&s.control))}o.push_str("]\n}\n");o}}
fn proj(p:Option<ProjectileSnapshot>)->String{p.map_or("null".into(),|v|format!("{{\"x\":{},\"y\":{}}}",v.x,v.y))}fn esc(s:&str)->String{s.replace('\\',"\\\\").replace('"',"\\\"").replace('\n',"\\n")}
